#!/bin/zsh
# macOS 13 tested
#

brew install "awscli"
brew install "azure-cli"
brew install "bash"
brew install "bash-completion", link: false
brew install "bash-completion@2"
brew install "bat"
brew install "caddy"
brew install "ffmpeg"
brew install "exiftool"
brew install "gh"
brew install "git"
brew install "git-gui"
brew install "git-lfs"
brew install "go"
brew install "go-jsonnet"
brew install "goreleaser"
brew install "nghttp2"
brew install "helm"
brew install "htop"
brew install "httpie"
brew install "iftop"
brew install "imagemagick"
brew install "infracost"
brew install "jq"
brew install "json-glib"
brew install "kind"
brew install "kompose"
brew install "kubernetes-cli"
brew install "krew"
brew install "kube-ps1"
brew install "kubectx"
brew install "kubeval"
brew install "kustomize"
brew install "libosinfo"
brew install "lynx"
brew install "mas"
brew install "midnight-commander"
brew install "minica"
brew install "minikube"
brew install "mongocli"
brew install "moreutils"
brew install "mysql-client"
brew install "mysql-client@5.7"
brew install "openconnect"
brew install "podman"
brew install "rancher-cli"
brew install "rke"
brew install "starship"
brew install "telnet"
brew install "terraform"
brew install "terraform-docs"
brew install "tflint"
brew install "thefuck"
brew install "tig"
brew install "tree"
brew install "watch"
brew install "wget"
brew install "wifi-password"
brew install "wireguard-tools"
brew install "youtube-dl", link: false
brew install "yq"
brew install "hashicorp/tap/vault"


brew install cask "obs"
brew install cask "slack"
brew install cask "signal"
brew install cask "spotify"
# brew install cask "vmware-fusion" # no ARM support yet
brew install cask "zoom"
brew install cask "pgadmin4"


