# customized for: Stanislav Musil <musil@sm-net.cz>
#####################################

STANISLAV_MUSIL_DESKTOP_HOSTNAMES=" STANs-MacBook-Pro-14-M1-MAX.local HP-Fury-G8 workstation win11smu "

export EDITOR=/usr/bin/vi

# Git configuration for Stanislav Musil's desktop only (also for SSH forward)
if [[ $STANISLAV_MUSIL_DESKTOP_HOSTNAMES =~ " $HOSTNAME " ]]; then
  export GIT_AUTHOR_NAME="Stanislav Musil"
  export GIT_AUTHOR_EMAIL="musil@sm-net.cz"
  export GIT_COMMITTER_NAME=$GIT_AUTHOR_NAME
  export GIT_COMMITTER_EMAIL=$GIT_AUTHOR_EMAIL
  export DOCKER_HUB_USER="stmusil"

fi

# Set up the prompt
autoload -Uz promptinit
promptinit
prompt adam1

setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
# eval "$(dircolors -b)" . #not in mac
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'


################### OH MY ZSH --START-- #############################
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"
#ZSH_THEME="agnoster"
#plugins=(git kube-ps1 docker docker-compose)
plugins=(git 1password ansible bbedit argocd docker docker-compose dotenv git github gitignore git-prompt golang history jira kube-ps1 kubectl kubectx macos pyenv python qrcode sudo terraform vscode)
if [ -f $ZSH/oh-my-zsh.sh ]; then
  source $ZSH/oh-my-zsh.sh
fi
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

################### OH MY ZSH -- END -- #############################


# fix issue with signing commits
export GPG_TTY=$(tty)

# Set language for MC
export LANG=en_US.UTF-8


# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# ~/bin

[ -d "${HOME}/bin" ] && export PATH="${HOME}/bin:${PATH}"

# Add BIN to PATH for scripting. Make sure this is the last PATH variable change.
export PATH=$PATH:$HOME/bin

[ -d "$HOME/go/bin" ] && export PATH="$HOME/go/bin:$PATH"

# Individual history per tab
#
# See: https://superuser.com/a/1248123/675796
unsetopt inc_append_history
unsetopt share_history


# General
alias ls='ls -al'
alias ll='ls -al'
alias la='ls -A'
alias lt='ls -alt'
alias lst='ls -alt'
alias lstr='ls -altr'
alias lsr='ls -alr'

alias p='ping -c 4'
alias p8='ping -c 4 8.8.8.8'

# SSH with private key
alias sshi='ssh -i ~/.ssh/SMU_ed25519-key-20200423-OpenSSH'
alias sshim='ssh -i ~/.ssh/SMU_ed25519-key-20200423-OpenSSH -l musils'
alias sshir='ssh -i ~/.ssh/SMU_ed25519-key-20200423-OpenSSH -l root'
alias sshia='ssh -i ~/.ssh/SMU_ed25519-key-20200423-OpenSSH -l ansible'

# new systems with python 3.x
alias httpserver="python3 -m http.server 8888"
alias phpserver="php -S localhost:$1 $2"

alias rmlog="find . -name '*.log' -exec rm -rf {} \;"
alias rmswp="find . -name '*.swp' -exec rm -rf {} \;"
alias rmdsstore="find . -name '.DS_Store' -exec rm -rf {} \;"


# Git
alias g=git
#complete -F _complete_alias g
alias gst='git status'
#complete -F _complete_alias gst
alias gsta='git status --untracked-files=all'
#complete -F _complete_alias gsta
alias gdi='git diff'
#complete -F _complete_alias gdi
alias gdis='git diff --staged'
#complete -F _complete_alias gdis
alias gdit='git diff | tig'
#complete -F _complete_alias gdit
alias gdist='git diff --staged | tig'
#complete -F _complete_alias gdist
alias gci='git commit -S'
#complete -F _complete_alias gci
alias gco='git checkout'
#complete -F _complete_alias gco
alias gbr='git branch'
#complete -F _complete_alias gbr
alias gad='git add'
#complete -F _complete_alias gad
alias gfa='git fetch --all --prune'
#complete -F _complete_alias gfa
alias gtka='gitk --all'
#complete -F _complete_alias gtka
alias gcm='git commit -m '
#complete -F _complete_alias gcm
alias gcms='git commit -S -m '
#complete -F _complete_alias gcms
alias gacp='git add . && git commit && git push'
#complete -F _complete_alias gacp


# Kubernetes
alias k=kubectl
alias kx=kubectx
alias kn=kubens

alias kdev="kubectl run dev-$(date +%s) --rm -ti --image sikalabs/dev -- bash"

# --- Kubernetes ---
alias k='kubectl'
source <(kubectl completion zsh)
#complete -F __start_kubectl k

# install: brew install kubectx
# kubectx
alias kx=kubectx
#complete -F _complete_alias kx

# kubens
alias kn=kubens
#complete -F _complete_alias kn

# kube-ps1
# function kps1() {
#   source "/usr/local/opt/kube-ps1/share/kube-ps1.sh"
#   export KUBE_PS1_SYMBOL_ENABLE=false
#   export PS1='$(kube_ps1)'$PS1
# }

# krun
alias krun="kubectl run kubeshell -ti --rm --image nixery.dev/shell/kubectl/curl/host/telnet/wget/vim/mc/htop/less -- bash"

# ksys
alias ksys="kubectl -n kube-system"
#complete -F _complete_alias ksys

# klogs
alias klogs="kubectl logs"
#complete -F _complete_alias klogs

# kports
alias kports="kubectl port-forward"
#complete -F _complete_alias kports



# Terraform
alias tf=terraform
#complete -F _complete_alias tf

# Terraform Shortcuts
alias tfi="terraform init"
#complete -F _complete_alias tfi

alias tfa="terraform apply"
#complete -F _complete_alias tfa

alias tfd="terraform destroy"
#complete -F _complete_alias tfd

alias tfp="terraform plan"
#complete -F _complete_alias tfp

alias tfs="terraform show"
#complete -F _complete_alias tfs

alias tfo="terraform output"
#complete -F _complete_alias tfo

alias tip='terraform init && terraform plan'
alias tipa='terraform init && terraform plan && terraform apply'

function commit-terraform-lock() {
  git add .terraform.lock.hcl
  git commit -m "[generated] Update .terraform.lock.hcl"
}


# Terraform autocompletition
autoload -U +X bashcompinit && bashcompinit
#complete -o nospace -C /opt/homebrew/bin/terraform terraform

# ArgoCD
if [ -f /opt/homebrew/bin/argocd ]; then
. <(argocd completion zsh); compdef _argocd argocd
fi


alias acd="argocd "

# slu
if [ -f /opt/homebrew/bin/slu ]; then
. <(slu completion zsh); compdef _slu slu
fi

# tergum
if [ -f /opt/homebrew/bin/tergum ]; then
. <(tergum completion zsh); compdef _tergum tergum
fi

# training-cli
if [ -f /opt/homebrew/bin/training-cli ]; then
. <(training-cli completion zsh); compdef _training-cli training-cli
fi

# watch
alias watch="watch "
alias w="watch -n 0.3 "


# Terraform Plugin Cache (save plugins in one dir to save space)
export TF_PLUGIN_CACHE_DIR="$HOME/.terraform-plugin-cache"

# Docker
alias dra='docker ps -a -q | xargs -r docker rm -f'
alias docker-compose="docker compose "

# youtube-dl mp3
alias yd='youtube-dl --extract-audio --audio-format mp3 '

# wget
alias wget='wget -q --show-progress --https-only --timestamping'


# History
# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
export HISTFILE=~/.zsh_history
export HISTSIZE=999999999
export SAVEHIST=$HISTSIZE
export HISTORY_IGNORE="(MAGICSHIT|*ACCESS_KEY*|*SECRET_KEY*|*TOKEN*)"

# Matrix 
alias matrix='cmatrix -b -C green -s'
