#!/bin/bash
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# ogirinal: Ondrej Sika <ondrej@ondrejsika.com>  https://github.com/ondrejsika/dotfiles
# customized for: Stanislav Musil <musil@sm-net.cz>
#####################################

STANISLAV_MUSIL_DESKTOP_HOSTNAMES=" workstation xps17 HP-Fury-G8 "

export EDITOR=/usr/bin/vi

# Git configuration for Stanislav Musil's desktop only (also for SSH forward)
if [[ $STANISLAV_MUSIL_DESKTOP_HOSTNAMES =~ " $HOSTNAME " ]]; then
  export GIT_AUTHOR_NAME="Stanislav Musil"
  export GIT_AUTHOR_EMAIL="musil@sm-net.cz"
  export GIT_COMMITTER_NAME=$GIT_AUTHOR_NAME
  export GIT_COMMITTER_EMAIL=$GIT_AUTHOR_EMAIL
fi

# Set language for MC
export LANG=en_US.UTF-8

# Bash history settings
export HISTCONTROL=ignoreboth
export HISTSIZE=1000000
export HISTFILESIZE=2000000
shopt -s histappend

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes
if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
        # We have color support; assume it's compliant with Ecma-48
        # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
        # a case would tend to support setf rather than setaf.)
        color_prompt=yes
    else
        color_prompt=
    fi
fi
if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

#
export PATH=$PATH:/home/musils/bin

[ -d "$HOME/go/bin" ] && export PATH="$HOME/go/bin:$PATH"


# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi
# See /usr/share/doc/bash-doc/examples in the bash-doc package.
# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi


alias t='terraform'
alias ti='terraform init'
alias tp='terraform plan'
alias ta='terraform apply'
alias tip='terraform init && terraform plan'
alias tipa='terraform init && terraform plan && terraform apply'
alias tv='terraform validate'

#alias w="watch -n 0.3"
#alias cc="xclip -sel clip"

alias httpserve="python -m SimpleHTTPServer"
alias phpserve="php -S localhost:$1 $2"

#alias tl="telnet 127.0.0.1"

#alias activate="source .env/bin/activate"

alias rmlog="find . -name '*.log' -exec rm -rf {} \;"
alias rmswp="find . -name '*.swp' -exec rm -rf {} \;"
alias rmdsstore="find . -name '.DS_Store' -exec rm -rf {} \;"

# GIT aliases

alias g=git
complete -F _complete_alias g
alias gst='git status'
complete -F _complete_alias gst
alias gsta='git status --untracked-files=all'
complete -F _complete_alias gsta
alias gdi='git diff'
complete -F _complete_alias gdi
alias gdis='git diff --staged'
complete -F _complete_alias gdis
alias gdit='git diff | tig'
complete -F _complete_alias gdit
alias gdist='git diff --staged | tig'
complete -F _complete_alias gdist
alias gci='git commit -S'
complete -F _complete_alias gci
alias gco='git checkout'
complete -F _complete_alias gco
alias gbr='git branch'
complete -F _complete_alias gbr
alias gad='git add'
complete -F _complete_alias gad
alias gfa='git fetch --all --prune'
complete -F _complete_alias gfa
alias gtka='gitk --all'
complete -F _complete_alias gtka

alias gacp='git add . && git commit && git push'
complete -F _complete_alias gacp


alias ll='ls -al'
alias la='ls -A'
alias l='ls -CF'

#alias createutfdb="createdb -l en_US.utf8 -E UTF8 -T template0"

alias yd='youtube-dl --extract-audio --audio-format mp3 '

# --- Kubernetes ---
alias k='kubectl'
source <(kubectl completion bash)
complete -F __start_kubectl k

# install: brew install kubectx
# kubectx
alias kx=kubectx
complete -F _complete_alias kx

# kubens
alias kn=kubens
complete -F _complete_alias kn

# kube-ps1
# function kps1() {
#   source "/usr/local/opt/kube-ps1/share/kube-ps1.sh"
#   export KUBE_PS1_SYMBOL_ENABLE=false
#   export PS1='$(kube_ps1)'$PS1
# }

# krun
alias krun="kubectl run kubeshell -ti --rm --image nixery.dev/shell/kubectl/curl/host/telnet/wget/vim/mc/htop/less -- bash"

# ksys
alias ksys="kubectl -n kube-system"
complete -F _complete_alias ksys

# klogs
alias klogs="kubectl logs"
complete -F _complete_alias klogs

# kports
alias kports="kubectl port-forward"
complete -F _complete_alias kports

# Docker
alias dra="docker ps -a  -q | xargs docker rm -f"

# Terraform
alias tf=terraform
complete -F _complete_alias tf

# Terraform Shortcuts
alias tfi="terraform init"
complete -F _complete_alias tfi

alias tfa="terraform apply"
complete -F _complete_alias tfa

alias tfd="terraform destroy"
complete -F _complete_alias tfd

alias tfp="terraform plan"
complete -F _complete_alias tfp

alias tfs="terraform show"
complete -F _complete_alias tfs

alias tfo="terraform output"
complete -F _complete_alias tfo

alias tip='terraform init && terraform plan'
alias tipa='terraform init && terraform plan && terraform apply'


function commit-terraform-lock() {
  git add .terraform.lock.hcl
  git commit -m "[generated] Update .terraform.lock.hcl"
}


# BASH debian default config
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
fi

# Support for local bashrc, bash aliases
if [ -z $LOCAL_BASHRC_LOADED ]; then
    if [ -f ~/.bashrc ]; then
        export LOCAL_BASHRC_LOADED=yes
        . ~/.bashrc
    fi
fi

# Enable autocomplete
#if ! shopt -oq posix; then
#  if [ -f /usr/share/bash-completion/bash_completion ]; then
#    . /usr/share/bash-completion/bash_completion
#  elif [ -f /etc/bash_completion ]; then
#    . /etc/bash_completion
#  fi
#fi
