#!/bin/bash
mkdir $1
cd $1
touch README.md
git init
git add README.md
git remote add origin git@gitlab.int.dc5.cz:musils/$1.git
git push --set-upstream origin main
git add .
git commit -m "Initial commit"
git push -u origin master
